SEND_TOKEN = "{TERMII_ENDPOINT_URL}/api/sms/otp/call"
SEND_VOICE_TOKEN = "{TERMII_ENDPOINT_URL}/api/sms/otp/send/voice"
SEND_EMAIL_TOKEN = "{TERMII_ENDPOINT_URL}/api/email/otp/send"
VERIFY_TOKEN = "{TERMII_ENDPOINT_URL}/api/sms/otp/verify"
IN_APP_TOKEN = "{TERMII_ENDPOINT_URL}/api/sms/otp/generate"
